# ============================================================
# Export Seurat objects for SAMap
#
# Writes:
#   matrix.mtx   - log-normalized RNA expression (genes x cells)
#   genes.txt    - gene names
#   cells.txt    - cell barcodes
#   metadata.csv - Seurat metadata with a cell_id column
#
# The exported files are converted to AnnData by:
#   python/samap/make_h5ad.py
# ============================================================

library(Seurat)
library(Matrix)
library(readr)


export_for_samap <- function(
    object,
    output_dir,
    normalize_if_needed = TRUE
) {
  if (!inherits(object, "Seurat")) {
    stop("`object` must be a Seurat object.")
  }

  if (!"RNA" %in% Assays(object)) {
    stop("The Seurat object does not contain an RNA assay.")
  }

  dir.create(
    output_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  DefaultAssay(object) <- "RNA"

  # Join Seurat v5 RNA layers before matrix export.
  object <- JoinLayers(
    object,
    assay = "RNA"
  )

  rna_layers <- Layers(object[["RNA"]])

  # SAMap input in this project used the log-normalized RNA data layer.
  if (!"data" %in% rna_layers) {
    if (!normalize_if_needed) {
      stop(
        "RNA assay does not contain a normalized `data` layer. ",
        "Run NormalizeData() first or set normalize_if_needed = TRUE."
      )
    }

    object <- NormalizeData(
      object,
      assay = "RNA",
      normalization.method = "LogNormalize",
      scale.factor = 10000,
      verbose = FALSE
    )
  }

  expr <- GetAssayData(
    object,
    assay = "RNA",
    layer = "data"
  )

  metadata <- object[[]]
  metadata$cell_id <- rownames(metadata)
  metadata <- metadata[colnames(expr), , drop = FALSE]

  Matrix::writeMM(
    expr,
    file.path(output_dir, "matrix.mtx")
  )

  readr::write_lines(
    rownames(expr),
    file.path(output_dir, "genes.txt")
  )

  readr::write_lines(
    colnames(expr),
    file.path(output_dir, "cells.txt")
  )

  write.csv(
    metadata,
    file.path(output_dir, "metadata.csv"),
    row.names = FALSE
  )

  message(
    "Exported ",
    nrow(expr),
    " genes x ",
    ncol(expr),
    " cells to ",
    normalizePath(output_dir, mustWork = FALSE)
  )

  invisible(object)
}


# ------------------------------------------------------------
# Example usage
# ------------------------------------------------------------
# These objects are generated by the species-level scripts.
#
# human_fib <- readRDS("outputs/human_fibroblasts.rds")
# mouse_fib <- readRDS("outputs/mouse_fibroblasts.rds")
# pig_fib <- readRDS("outputs/pig_fibroblasts.rds")
# chicken_fib <- readRDS("outputs/chicken_fibroblasts.rds")
# zebrafish_fib <- readRDS("outputs/zebrafish_fibroblasts.rds")
# tilapia_fib <- readRDS("outputs/tilapia_fibroblasts.rds")
#
# export_for_samap(human_fib, "outputs/preprocessing/samap_exports/human")
# export_for_samap(mouse_fib, "outputs/preprocessing/samap_exports/mouse")
# export_for_samap(pig_fib, "outputs/preprocessing/samap_exports/pig")
# export_for_samap(chicken_fib, "outputs/preprocessing/samap_exports/chicken")
# export_for_samap(zebrafish_fib, "outputs/preprocessing/samap_exports/zebrafish")
# export_for_samap(tilapia_fib, "outputs/preprocessing/samap_exports/tilapia")
